# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howler_app', '0003_remove_howler_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howler',
            name='creation_date',
        ),
    ]
