# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howler_app', '0004_remove_howler_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Howler',
        ),
    ]
