# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howler_app', '0006_howler'),
    ]

    operations = [
        migrations.AddField(
            model_name='howler',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
