# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howler_app', '0007_howler_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='howler_app.UserProfile'),
        ),
    ]
