# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howler_app', '0010_auto_20171125_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
    ]
