# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howler_app', '0011_auto_20171125_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_picture/blankgravatar.jpg', upload_to='profile_picture'),
        ),
    ]
